name: 🚀

on:
  pull_request: { }
  push: { branches: [ main ] }

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: install dependencies
        run: yarn && yarn --cwd ./functions
      - name: run linter
        run: yarn lint && yarn --cwd ./functions lint
      - name: run tests
        run: yarn test && yarn --cwd ./functions test
#      - name: Upload test results
#        uses: actions/upload-artifact@v1
#        with:
#          name: Test results
#          path: "**/artifacs"

  build:
    name: 🛠 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: install dependencies
        run: yarn && yarn --cwd ./functions
      - name: build
        run: yarn --cwd ./functions build

  deploy:
    name: ✨ Deploy
    needs: [ test, build ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: install dependencies
        run: yarn && yarn --cwd ./functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v11.24.1
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
